"""crear tabla invoice_records

Revision ID: 331bf3a3f12c
Revises:
Create Date: 2026-08-30 02:56:41.119761

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "331bf3a3f12c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("imap_uid", sa.Integer(), nullable=False),
        sa.Column("mailbox_account", sa.String(), nullable=False),
        sa.Column("sender_email", sa.String(), nullable=False),
        sa.Column("received_date", sa.DateTime(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("body_preview", sa.String(), nullable=True),
        sa.Column("has_attachments", sa.Boolean(), nullable=False),
        sa.Column("attachment_filename", sa.String(), nullable=True),
        sa.Column("attachment_hash", sa.String(), nullable=True),
        sa.Column("attachment_size_bytes", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_detail", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    op.create_index(op.f("ix_invoice_records_received_date"), "invoice_records", ["received_date"], unique=False)
    op.create_index(op.f("ix_invoice_records_sender_email"), "invoice_records", ["sender_email"], unique=False)
    op.create_index(op.f("ix_invoice_records_status"), "invoice_records", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_records_status"), table_name="invoice_records")
    op.drop_index(op.f("ix_invoice_records_sender_email"), table_name="invoice_records")
    op.drop_index(op.f("ix_invoice_records_received_date"), table_name="invoice_records")
    op.drop_table("invoice_records")
    # ### end Alembic commands ###
