"""Add financial columns

Revision ID: e0a8525fe55e
Revises: 331bf3a3f12c
Create Date: 2026-08-30 10:46:34.872888

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0a8525fe55e"
down_revision: str | Sequence[str] | None = "331bf3a3f12c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice_records", sa.Column("issuer_id", sa.String(length=50), nullable=True))
    op.add_column("invoice_records", sa.Column("issuer_name", sa.String(length=255), nullable=True))
    op.add_column("invoice_records", sa.Column("invoice_number", sa.String(length=100), nullable=True))
    op.add_column("invoice_records", sa.Column("issue_date", sa.DateTime(), nullable=True))
    op.add_column("invoice_records", sa.Column("currency", sa.String(length=10), nullable=True))
    op.add_column("invoice_records", sa.Column("subtotal", sa.Float(), nullable=True))
    op.add_column("invoice_records", sa.Column("tax_amount", sa.Float(), nullable=True))
    op.add_column("invoice_records", sa.Column("total_amount", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoice_records", "total_amount")
    op.drop_column("invoice_records", "tax_amount")
    op.drop_column("invoice_records", "subtotal")
    op.drop_column("invoice_records", "currency")
    op.drop_column("invoice_records", "issue_date")
    op.drop_column("invoice_records", "invoice_number")
    op.drop_column("invoice_records", "issuer_name")
    op.drop_column("invoice_records", "issuer_id")
    # ### end Alembic commands ###
